---
title: 'Java异常处理'
date: 2021-09-30
permalink: /posts/2021/09/java-1/
tags:
  - JAVA
  - 异常处理
  - 基础语法
---

## Java异常处理

### 一、异常的概念

1、异常：程序在运行过程中发生的不正常现象

2、异常出现的原因：程序交付之前，不可能穷举程序运行过程中出现的所有情况

3、异常给程序带的危害：
		·	得不到正常结果，得到异常提示（乱码）
		·	程序出现异常，即刻退出，不执行后面的代码

### 二、异常的就地捕获

1、try：将可能出现异常的代码放在try块中

2、catch：将出现异常后要处理异常的代码放在catch块中（一个try后可以有多个catch）

3、finally：try-catch后面可以接1个finally块。finally里面放置"不管是否出现异常，都必须要执行"的代码：比不放finally可靠性高

4、原理：try块中的代码如果没有异常，不执行catch；如果出现异常，掠过try块中剩余代码，转而执行catch中的代码，执行完毕，程序继续向后执行

5、Java中常见的异常有哪些？
		·	ArithmeticException: 算术异常，如除数为0
		·	ArrayIndexOutOfBoundsException：数组越界异常
		·	NullPointerException：未分配内存异常
		·	NumberFormatException：数字格式异常

```java
//输入一个数，显示其平方
class Test{
	public static void main(String[] args)
    {
	   while(true)
       {
           try
           {	
               String s = javax.swing.JOptionPane.showInputDialog("输入数字");
               int n = Integer.parseInt(s);
               int r = n * n;
               System.out.println("结果是:" + r);
               break;
           }
           catch(NumberFormatException e)		//若数字格式异常，则执行这一指令
           {
               System.out.println("数字格式异常，请检查");
           }
           catch(ArithmeticException e)			//若算术运算异常，则执行这一指令
           {
               System.out.println("算术运算异常，请检查");
           }
           catch(Exception e)					//若出现异常，且前面没有捕获，则此处捕获
           {
            System.out.println("以上代码出现异常，请检查");
           }
	   }
	}	
}
```

### 三、异常的向前抛出

1、throw：在函数中抛出具体的异常

2、throws：标记某个函数可能抛出异常

3、将需要将异常向前抛出的函数加上一个标记：throws XXXException ，表示可能向前抛出某种异常

4、异常抛出后还可以再次抛出，在某一个函数中捕获即可（至少得在main函数中被捕获，main函数抛出则直接进入系统，操作无意义）

```java
class Test{
	int setAge(int age) throws Exception{			//标记该函数可能抛出异常
		if(age>100 || age<0){
			Exception e = new Exception("年龄范围错误");
			throw e;								//包装成异常并抛出
		}
		return age;		
	}
	public static void main(String[] args){
	  	Test t = new Test();
	  	try{										//异常的就地捕获
	  		t.setAge(-100);
	  	}catch(Exception e){
	  		System.out.println(e.getMessage());
	  	}
	}	
}
```

